### ISSUE TITLE
Crash during parsing in predict_next

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#1033]
If someone runs the following code, the SegFault is observed:
```
src/luajit -e '
local _
for _ in (nil):foo() do end
'
Segmentation fault (core dumped)
```

Backtrace is the following:
```
0x000055555558a9d5 in predict_next (ls=0x7fffffffd260, fs=0x7fffffffcd50, pc=2) at lj_parse.c:2521
2521        name = gco2str(gcref(var_get(ls, fs, bc_d(ins)).name));

#0  0x000055555558a9d5 in predict_next (ls=0x7fffffffd260, fs=0x7fffffffcd50, pc=2) at lj_parse.c:2521
#1  0x000055555558add8 in parse_for_iter (ls=0x7fffffffd260, indexname=0x7ffff7c838f0) at lj_parse.c:2566
#2  0x000055555558b027 in parse_for (ls=0x7fffffffd260, line=3) at lj_parse.c:2596
#3  0x000055555558b2c3 in parse_stmt (ls=0x7fffffffd260) at lj_parse.c:2657
#4  0x000055555558b3d3 in parse_chunk (ls=0x7fffffffd260) at lj_parse.c:2704
#5  0x000055555558b818 in lj_parse (ls=0x7fffffffd260) at lj_parse.c:2738
#6  0x000055555558bc44 in cpparser (L=0x7ffff7c81380, dummy=0x0, ud=0x7fffffffd260) at lj_load.c:41
#7  0x00005555555ab164 in lj_vm_cpcall ()
#8  0x000055555558bf51 in lua_loadx (L=0x7ffff7c81380, reader=0x55555558c420 <reader_string>, data=0x7fffffffd370, 
    chunkname=0x7ffff7c8afa0 "\nlocal _\nfor _ in (nil):foo() do end\n", mode=0x0) at lj_load.c:58
#9  0x000055555558c4cb in luaL_loadbufferx (L=0x7ffff7c81380, buf=0x7ffff7c8afa0 "\nlocal _\nfor _ in (nil):foo() do end\n", size=37, 
    name=0x7ffff7c8afa0 "\nlocal _\nfor _ in (nil):foo() do end\n", mode=0x0) at lj_load.c:143
#10 0x00005555556252c2 in lj_cf_load (L=0x7ffff7c81380) at lib_base.c:426
#11 0x0000555555625374 in lj_cf_loadstring (L=0x7ffff7c81380) at lib_base.c:439
#12 0x00005555555aad6e in lj_BC_FUNCC ()
#13 0x000055555557b2d9 in lua_pcall (L=0x7ffff7c81380, nargs=3, nresults=0, errfunc=0) at lj_api.c:1145
#14 0x000055555555da2e in dobytecode (L=0x7ffff7c81380, argv=0x7fffffffd748) at luajit.c:389
#15 0x000055555555dfc5 in runargs (L=0x7ffff7c81380, argv=0x7fffffffd728, argn=2) at luajit.c:483
#16 0x000055555555e1cc in pmain (L=0x7ffff7c81380) at luajit.c:546
#17 0x00005555555aad6e in lj_BC_FUNCC ()
#18 0x000055555557b6b8 in lua_cpcall (L=0x7ffff7c81380, func=0x55555555e068 <pmain>, ud=0x0) at lj_api.c:1173
#19 0x000055555555e361 in main (argc=4, argv=0x7fffffffd728) at luajit.c:581
```

The reason is that the first slot doesn't contain a local variable:
```
(gdb) p /x var_get(ls, fs, bc_d(ins))
$1 = {name = {gcptr64 = 0x4}, startpc = 0x65646570, endpc = 0x74732066, slot = 0x72, info = 0x75}
```

The emitted bytecode at this moment is the following:
```
0001    KNIL     0   1
0002    MOV      3   1
0003    TGETS    1   1   0  ; "foo"
0004    CALL     1   4   2
```

The `KPRI 1 0` is merged with `KPRI 0 0` in `bcemit_method()` by `expr_toanyreg()` to the resulting `KNIL 0 1`. The top register from `KNIL` is copied as the first argument by `MOV 3 1` but it has no name as far as it's not a variable. So, when we try to lookup it, we got a crash.

AFAICS, there is not other `MOV` that can refer merged `nil`, so we can just check that the `MOV` doesn't follow the `KNIL` with the corresponding top slot (i.e. there is no need to compare with the `KNIL` range):

This patch fixes things for me:
```diff
diff --git a/src/lj_parse.c b/src/lj_parse.c
index 64ae2c16..717466da 100644
--- a/src/lj_parse.c
+++ b/src/lj_parse.c
@@ -2517,9 +2517,14 @@ static int predict_next(LexState *ls, FuncState *fs, BCPos pc)
   GCstr *name;
   cTValue *o;
   switch (bc_op(ins)) {
-  case BC_MOV:
-    name = gco2str(gcref(var_get(ls, fs, bc_d(ins)).name));
+  case BC_MOV: {
+    BCIns ip = fs->bcbase[pc - 1].ins;
+    BCReg mov_src = bc_d(ins);
+    if (bc_op(ip) == BC_KNIL && bc_d(ip) == mov_src)
+      return 0;
+    name = gco2str(gcref(var_get(ls, fs, mov_src).name));
     break;
+  }
   case BC_UGET:
     name = gco2str(gcref(ls->vstack[fs->uvmap[bc_d(ins)]].name));
     break;
```

**Comment by MikePall** [comment]
I've committed a simpler fix. Thanks!
