### ISSUE TITLE
Red zone overflow on trace compilation

### ISSUE THREAD

**Issue by ligurio** [LuaJIT/LuaJIT#1116]
If someone runs the following Lua code by LuaJIT built with enabled `LUA_USE_ASSERT`, the segmentation fault is observed:

```lua
jit.opt.start('hotloop=1')

a = 0
b = 0
c = 0
d = 0
e = 0
f = 0
g = 0
h = 0
i = 0
j = 0
y = 0
k = 0
l = 0
m = 0
n = 0
o = 0
z = 0
p = 0
q = 0
r = 0
s = 0
t = 0
u = 0
v = 0
w = 0

for x = 2.000, 10.5 do
  a = a + 1
  do b = b + 1
    do c = c + 1
	  do d = d + 1
	    for x = x, 3.000 do
		  e = e + 1
		end
	  for x = 3.000, x do
	    f = f + 1
		do
		  do
		    g = g + 1
			  do h = h + 1
			    do i = i + 1
				  do j = j + 1
				    y = y + 1
				  end
				end
			  end
			end
		  end
		end
		k = k + 1
		do
		  do
		    l = l + 1
			do
			  m = m + 1
			  do
			    n = n + 1
				do
				  o = o + 1
				  z = z + 1
				end
			  end
			end
		  end
		end
	  end
	  p = p + 1
	  do
	    q = q + 1
		do
		  r = r + 1
		  s = s + 1
		end
	  end
	end
  end
  for x = x, 3.001 do
    aa = a
	do
	  t = t + 1
	  do
	    u = u + 1
		do
		  v = v + 1
		  w = w + 1
		end
	  end
	end
  end
end
```

Backtrace is the following:

```c++
LuaJIT ASSERT lj_asm.c:148: checkmclim: red zone overflow: 0x1efdfd20 IR 0217  91 0093 -19858

AddressSanitizer:DEADLYSIGNAL
=================================================================
==461==ERROR: AddressSanitizer: ABRT on unknown address 0x0000000001cd (pc 0x7fba5a00c00b bp 0x7ffdaf257ad0 sp 0x7ffdaf257770 T0)
SCARINESS: 10 (signal)
    #0 0x7fba5a00c00b in raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: e678fe54a5d2c2092f8e47eb0b33105e380f7340)
    #1 0x7fba59feb858 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x22858) (BuildId: e678fe54a5d2c2092f8e47eb0b33105e380f7340)
    #2 0x6e38a1 in lj_assert_fail /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_assert.c:25:3
    #3 0x7a188e in lj_asm_trace /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_asm.c
    #4 0x6bc180 in trace_state /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_trace.c:732:7
    #5 0x6e16b3 in lj_vm_cpcall /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_vm.S:1250
    #6 0x6b9737 in lj_trace_ins /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_trace.c:764:10
    #7 0x6757ac in lj_dispatch_ins /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_dispatch.c:423:7
    #8 0x6e303d in lj_vm_inshook /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_vm.S:2473
    #9 0x6871e5 in lua_pcall /src/lua-c-api-tests/build/luajit-v2.1/source/src/lj_api.c:1150:12
    #10 0x56f2b3 in TestOneProtoInput(lua_grammar::Block const&) /src/lua-c-api-tests/tests/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc:69:6
    #11 0x56f2b3 in LLVMFuzzerTestOneInput /src/lua-c-api-tests/tests/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc:34:1
    #12 0x440193 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #13 0x43f97a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:514:3
    #14 0x441049 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:757:19
    #15 0x441d15 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:895:5
    #16 0x43107f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #17 0x45a6d2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #18 0x7fba59fed082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: e678fe54a5d2c2092f8e47eb0b33105e380f7340)
    #19 0x421abd in _start (build-out/luaL_loadbuffer_proto_test+0x421abd)

DEDUP_TOKEN: raise--abort--lj_assert_fail
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: e678fe54a5d2c2092f8e47eb0b33105e380f7340) in raise
==461==ABORTING
```

In GDB:

```
LuaJIT ASSERT lj_asm.c:147: checkmclim: red zone overflow: 0x55551d33fdaf IR 0136  91 0028 -19858


Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352674176) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352674176) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737352674176) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737352674176, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005555555adebe in lj_assert_fail (g=0x7ffff7e7a3e0, file=0x55555566f5e3 "lj_asm.c", line=147, func=0x5555556708b8 <__func__.49> "checkmclim", 
    fmt=0x55555566f740 "red zone overflow: %p IR %04d  %02d %04d %04d\n") at lj_assert.c:25
#6  0x000055555560949e in checkmclim (as=0x7fffffffcd10) at lj_asm.c:147
#7  lj_asm_trace (J=0x7ffff7e7a6b8, T=0x7ffff7e7a6b8) at lj_asm.c:2568
#8  0x0000555555591671 in trace_state (L=0x7ffff7e7a380, dummy=0x0, ud=0x7ffff7e7a6b8) at lj_trace.c:732
#9  0x00005555555abd64 in lj_vm_cpcall ()
#10 0x0000555555591918 in lj_trace_ins (J=0x7ffff7e7a6b8, pc=0x7ffff7e7c718) at lj_trace.c:764
#11 0x0000555555569a67 in lj_dispatch_ins (L=0x7ffff7e7a380, pc=0x7ffff7e7c71c) at lj_dispatch.c:423
#12 0x00005555555ad6ee in lj_vm_inshook ()
#13 0x000055555557b82c in lua_pcall (L=0x7ffff7e7a380, nargs=0, nresults=-1, errfunc=2) at lj_api.c:1150
#14 0x000055555555cb46 in docall (L=0x7ffff7e7a380, narg=0, clear=0) at luajit.c:122
#15 0x000055555555d55f in handle_script (L=0x7ffff7e7a380, argx=0x7fffffffd670) at luajit.c:292
#16 0x000055555555e290 in pmain (L=0x7ffff7e7a380) at luajit.c:550
#17 0x00005555555ab96e in lj_BC_FUNCC ()
#18 0x000055555557bc13 in lua_cpcall (L=0x7ffff7e7a380, func=0x55555555e0d6 <pmain>, ud=0x0) at lj_api.c:1178
#19 0x000055555555e3d7 in main (argc=2, argv=0x7fffffffd668) at luajit.c:581
(gdb) 
```

Git bisect pointed to commit bd00094c3b50e193fb32aad79b7ea8ea6b78ed25, that enabled LJ_GC64 mode by default.
Further bisect with enabled `-DLUAJIT_ENABLE_GC64` pointed to a92e73023353e59405ebfdb2837b5742d17946a5, that adds LJ_GC64 mode interpreter. 

Env: Ubuntu 22.04.3 LTS, amd64
LuaJIT version: 69bbbf77363ceb00ad2653a7729a5c9e8316e61f

**Comment by corsix** [comment]
Looks like assembly of an IR instruction like:
```
0136 [80]  >  int CONV   0028  int.num check
```
Compiling to these 66 bytes of machine code:
```
11edbfdaf  cvttsd2si r15d, xmm5
11edbfdb4  xorps xmm9, xmm9
11edbfdb8  cvtsi2sd xmm9, r15d
11edbfdbd  ucomisd xmm5, xmm9
11edbfdc2  jnz 0x11edb00e5	->37
11edbfdc8  jpe 0x11edb00e5	->37
11edbfdce  mov [rsp+0x80], r15d
11edbfdd6  mov r15, [rsp+0xe8]
11edbfdde  movsd xmm9, [rsp+0xe0]
11edbfde8  movsd xmm5, [rsp+0xd8]
```
Notably, needs sufficient register pressure as to immediately spill the result of the instruction to the stack and then reload the three registers used by the instruction, and to have chosen enough registers with numbers >=8 (because shaving off a REX prefix or two would get 66 back down to <= 64), and to be using lots of spill slots (because memory offsets <= 0x7f are shorter to encode compared to those >= 0x80).

**Comment by corsix** [comment]
I would suggest the following patch:
```diff
diff --git a/src/lj_asm_x86.h b/src/lj_asm_x86.h
index 0e0b28a40d..d98fb82768 100644
--- a/src/lj_asm_x86.h
+++ b/src/lj_asm_x86.h
@@ -815,6 +815,7 @@ static void asm_tointg(ASMState *as, IRIns *ir, Reg left)
   emit_rr(as, XO_UCOMISD, left, tmp);
   emit_rr(as, XO_CVTSI2SD, tmp, dest);
   emit_rr(as, XO_XORPS, tmp, tmp);  /* Avoid partial register stall. */
+  checkmclim(as);
   emit_rr(as, XO_CVTTSD2SI, dest, left);
   /* Can't fuse since left is needed twice. */
 }
@@ -857,6 +858,7 @@ static void asm_conv(ASMState *as, IRIns *ir)
       emit_rr(as, XO_SUBSD, dest, bias);  /* Subtract 2^52+2^51 bias. */
       emit_rr(as, XO_XORPS, dest, bias);  /* Merge bias and integer. */
       emit_rma(as, XO_MOVSD, bias, k);
+      checkmclim(as);
       emit_mrm(as, XO_MOVD, dest, asm_fuseload(as, lref, RSET_GPR));
       return;
     } else {  /* Integer to FP conversion. */
@@ -1173,6 +1175,7 @@ static void asm_href(ASMState *as, IRIns *ir, IROp merge)
     asm_guardcc(as, CC_E);
   else
     emit_sjcc(as, CC_E, l_end);
+  checkmclim(as);
   if (irt_isnum(kt)) {
     if (isk) {
       /* Assumes -0.0 is already canonicalized to +0.0. */
@@ -1232,7 +1235,6 @@ static void asm_href(ASMState *as, IRIns *ir, IROp merge)
 #endif
   }
   emit_sfixup(as, l_loop);
-  checkmclim(as);
 #if LJ_GC64
   if (!isk && irt_isaddr(kt)) {
     emit_rr(as, XO_OR, tmp|REX_64, key);
@@ -1259,6 +1261,7 @@ static void asm_href(ASMState *as, IRIns *ir, IROp merge)
       emit_rr(as, XO_ARITH(XOg_SUB), dest, tmp);
       emit_shifti(as, XOg_ROL, tmp, HASH_ROT3);
       emit_rr(as, XO_ARITH(XOg_XOR), dest, tmp);
+      checkmclim(as);
       emit_shifti(as, XOg_ROL, dest, HASH_ROT2);
       emit_rr(as, XO_ARITH(XOg_SUB), tmp, dest);
       emit_shifti(as, XOg_ROL, dest, HASH_ROT1);
@@ -1276,7 +1279,6 @@ static void asm_href(ASMState *as, IRIns *ir, IROp merge)
       } else {
 	emit_rr(as, XO_MOV, tmp, key);
 #if LJ_GC64
-	checkmclim(as);
 	emit_gri(as, XG_ARITHi(XOg_XOR), dest, irt_toitype(kt) << 15);
 	if ((as->flags & JIT_F_BMI2)) {
 	  emit_i8(as, 32);
@@ -1554,6 +1556,7 @@ static void asm_ahuvload(ASMState *as, IRIns *ir)
   if (irt_islightud(ir->t)) {
     Reg dest = asm_load_lightud64(as, ir, 1);
     if (ra_hasreg(dest)) {
+      checkmclim(as);
       asm_fuseahuref(as, ir->op1, RSET_GPR);
       if (ir->o == IR_VLOAD) as->mrm.ofs += 8 * ir->op2;
       emit_mrm(as, XO_MOV, dest|REX_64, RID_MRM);
@@ -1601,6 +1604,7 @@ static void asm_ahuvload(ASMState *as, IRIns *ir)
   if (LJ_64 && irt_type(ir->t) >= IRT_NUM) {
     lj_assertA(irt_isinteger(ir->t) || irt_isnum(ir->t),
 	       "bad load type %d", irt_type(ir->t));
+    checkmclim(as);
 #if LJ_GC64
     emit_u32(as, LJ_TISNUM << 15);
 #else
```

The addition of `checkmclim(as);` to `asm_tointg` directly addresses the example given in this issue. The changes to `asm_conv` / `asm_href` / `asm_ahuvload` are based on manually auditing the rest of `lj_asm_x86.h`, looking for cases that might similarly exceed the red zone in particularly unlucky scenarios. Some of the changes _might_ be overly conservative, if I've overlooked some reason which would cause my worst-case estimation of emitted mcode size to not be hittable in practice.

**Comment by MikePall** [comment]
Fixed. Thanks!
