### ISSUE TITLE
stack-buffer-overflow in `narrow_conv_backprop`

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#1262]
To reproduce the issue, build LuaJIT with ASAN like the following:
```sh
make -j CCDEBUG=" -g -ggdb3" CFLAGS=" -O0" TARGET_CFLAGS="-fsanitize=address" TARGET_LDFLAGS="-fsanitize=address" XCFLAGS=" -DLUA_USE_APICHECK -DLUA_USE_ASSERT -DLUAJIT_USE_SYSMALLOC "
```

The reproducer </tmp/t.lua>:

```lua
local DEFAULT_NUMBER = 1
local tonumber = tonumber

local always_number = function(val)
  return tonumber(val) or DEFAULT_NUMBER
end

local add = function(v1, v2)
  return always_number(v1) + always_number(v2)
end

local counter_0 = 0
local counter_1 = 0
local counter_2 = 0
local tmp = add(nil, 'Name')
local Name0 = add(tmp, 'Name') -- Start long side trace here.
for _ = 0, 0, 0 do
  if counter_0 > 5 then break end
  counter_0 = counter_0 + 1

  for _ = always_number(false), 1, always_number(Name0) do
    if counter_1 > 5 then break end
    counter_1 = counter_1 + 1

    repeat
      if counter_2 > 5 then break end
      counter_2 = counter_2 + 1

      Name0 = Name0 + Name0 + Name0
      Name0 = add(Name0, nil) + Name0
    until nil
  end
end
```

Running the reproducer named </tmp/t.lua> with the following flags leads to the ASAN error:

```sh
src/luajit -Ohotexit=1 -Ohotloop=1 /tmp/t.lua
```

<details>

<summary> ASAN log: </summary>

```
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/burii/builds_workspace/luajit/asan/src/lj_opt_narrow.c:353 in narrow_conv_backprop
Shadow bytes around the buggy address:
  0x7ffff5b01980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7ffff5b01c00: 00 00 00 00 00 00 00 00[f3]f3 f3 f3 f3 f3 f3 f3
  0x7ffff5b01c80: f3 f3 f3 f3 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x7ffff5b01d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7ffff5b01e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==8792==ABORTING

#7  0x00007ffff79ece7e in __asan::ReportGenericError (pc=<optimized out>, bp=bp@entry=140737488338512, sp=sp@entry=140737488338496, addr=<optimized out>, 
    is_write=is_write@entry=true, access_size=access_size@entry=4, exp=<optimized out>, fatal=true)
    at /var/tmp/portage/sys-devel/gcc-13.3.1_p20240614/work/gcc-13-20240614/libsanitizer/asan/asan_report.cpp:485
#8  0x00007ffff79ee55e in __asan::__asan_report_store4 (addr=<optimized out>)
    at /var/tmp/portage/sys-devel/gcc-13.3.1_p20240614/work/gcc-13-20240614/libsanitizer/asan/asan_rtl.cpp:126
#9  0x00005555557aa6d1 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32800, depth=13) at lj_opt_narrow.c:345
#10 0x00005555557aa5b2 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32802, depth=12) at lj_opt_narrow.c:343
#11 0x00005555557aa5b2 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32805, depth=11) at lj_opt_narrow.c:343
#12 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32806, depth=10) at lj_opt_narrow.c:342
#13 0x00005555557aa5b2 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32808, depth=9) at lj_opt_narrow.c:343
#14 0x00005555557aa5b2 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32811, depth=8) at lj_opt_narrow.c:343
#15 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32812, depth=7) at lj_opt_narrow.c:342
#16 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32813, depth=6) at lj_opt_narrow.c:342
#17 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32814, depth=5) at lj_opt_narrow.c:342
#18 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32817, depth=4) at lj_opt_narrow.c:342
#19 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32818, depth=3) at lj_opt_narrow.c:342
#20 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32819, depth=2) at lj_opt_narrow.c:342
#21 0x00005555557aa554 in narrow_conv_backprop (nc=0x7ffff5b01820, ref=32820, depth=1) at lj_opt_narrow.c:342
#22 0x00005555557ab6e5 in lj_opt_narrow_convert (J=0x623000000440) at lj_opt_narrow.c:419
#23 0x000055555579bed1 in fold_narrow_convert (J=0x623000000440) at lj_opt_fold.c:1334
#24 0x00005555557a82a8 in lj_opt_fold (J=0x623000000440) at lj_opt_fold.c:2570
#25 0x0000555555683649 in rec_for (J=0x623000000440, fori=0x616000000168, isforl=0) at lj_record.c:534
#26 0x00005555556ad183 in lj_record_ins (J=0x623000000440) at lj_record.c:2597
#27 0x0000555555608498 in trace_state (L=0x623000000100, dummy=0x0, ud=0x623000000440) at lj_trace.c:705
#28 0x0000555555633b74 in lj_vm_cpcall ()
#29 0x0000555555609404 in lj_trace_ins (J=0x623000000440, pc=0x616000000168) at lj_trace.c:764
#30 0x00005555555aec37 in lj_dispatch_ins (L=0x623000000100, pc=0x61600000016c) at lj_dispatch.c:423
#31 0x0000555555635524 in lj_vm_inshook ()
#32 0x00005555555d338e in lua_pcall (L=0x623000000100, nargs=0, nresults=-1, errfunc=2) at lj_api.c:1151
#33 0x0000555555591e92 in docall (L=0x623000000100, narg=0, clear=0) at luajit.c:122
#34 0x0000555555592ceb in handle_script (L=0x623000000100, argx=0x7fffffffd570) at luajit.c:292
#35 0x0000555555594433 in pmain (L=0x623000000100) at luajit.c:550
#36 0x000055555563377e in lj_BC_FUNCC ()
#37 0x00005555555d3b2a in lua_cpcall (L=0x623000000100, func=0x55555559400d <pmain>, ud=0x0) at lj_api.c:1179
#38 0x0000555555594700 in main (argc=4, argv=0x7fffffffd558) at luajit.c:581
```

</details>

The reason is a missing check for the stack pointer after recursive calls during backpropagation across `ADD`/`SUB`:
https://github.com/LuaJIT/LuaJIT/blob/c68711cc872e6626dc9e653e94df7bf21691d38e/src/lj_opt_narrow.c#L341-L345

The following patch fixes the issue:
```diff
diff --git a/src/lj_opt_narrow.c b/src/lj_opt_narrow.c
index 1172df2b..02fb9e68 100644
--- a/src/lj_opt_narrow.c
+++ b/src/lj_opt_narrow.c
@@ -339,11 +339,12 @@ static int narrow_conv_backprop(NarrowConv *nc, IRRef ref, int depth)
     }
     if (++depth < NARROW_MAX_BACKPROP && nc->sp < nc->maxsp) {
       NarrowIns *savesp = nc->sp;
       int count = narrow_conv_backprop(nc, ir->op1, depth);
       count += narrow_conv_backprop(nc, ir->op2, depth);
-      if (count <= 1) {  /* Limit total number of conversions. */
+      /* Limit total number of conversions. */
+      if (count <= 1 && nc->sp < nc->maxsp) {
         *nc->sp++ = NARROWINS(IRT(ir->o, nc->t), ref);
         return count;
       }
       nc->sp = savesp;  /* Too many conversions, need to backtrack. */
     }
```

**Comment by MikePall** [comment]
Fixed. Thanks!
