### ISSUE TITLE
State is not restored during recording `__concat` metamethod in case of the OOM

### ISSUE THREAD

**Issue by Buristan** [LuaJIT/LuaJIT#1298]
The issue is similar to the #1234, but now we face OOM during the string allocation in the fold optimization.

<details>
  <summary> Reproducer script: </summary>

The file <t.lua>
```lua
local allocinject = require('allocinject')

jit.opt.start('hotloop=1')

local bigstr = string.rep('x', 2048)
local __concat = function()
  return 'concated'
end

-- Need to use metamethod call in the concat recording.
-- We may use any object with a metamethod, but let's use a table
-- as the most common one.
local concatable_t = setmetatable({}, {
  __concat = __concat,
})

local function concat_with_err()
  local counter = 0
  local r
  while counter < 1 do
    counter = counter + 1
    r = bigstr .. concatable_t .. ''
  end
  assert(false, "unreachable, should raise an error before")
end

allocinject.enable()
local e, r = pcall(concat_with_err)
allocinject.disable()
print(e, r)
```

The file <allocinject.c> to raise the OOM, where it is needed.
```c
#include "lua.h"
#include "lauxlib.h"

#undef NDEBUG
#include <assert.h>

static lua_Alloc old_allocf = NULL;
static void *old_alloc_state = NULL;

/* Function to be used instead of the default allocator. */
static void *allocf_with_injection(void *ud, void *ptr, size_t osize,
				   size_t nsize)
{
	assert(old_allocf != NULL);
	/* Check the specific string allocation. */
	if (osize == 0 && nsize > 2048)
		return NULL;
	return old_allocf(ud, ptr, osize, nsize);
}

static int enable(lua_State *L)
{
	assert(old_allocf == NULL);
	old_allocf = lua_getallocf(L, &old_alloc_state);
	lua_setallocf(L, allocf_with_injection, old_alloc_state);
	return 0;
}

static int disable(lua_State *L)
{
	assert(old_allocf != NULL);
	assert(old_allocf != allocf_with_injection);
	lua_setallocf(L, old_allocf, old_alloc_state);
	old_allocf = NULL;
	old_alloc_state = NULL;
	return 0;
}

static const struct luaL_Reg allocinject[] = {
	{"enable", enable},
	{"disable", disable},
	{NULL, NULL}
};

LUA_API int luaopen_allocinject(lua_State *L)
{
	luaL_register(L, "allocinject", allocinject);
	return 1;
}
```

How to build:
```sh
make -j CCDEBUG=" -g -ggdb3" CFLAGS=" -O0" XCFLAGS=" -DLUA_USE_APICHECK -DLUA_USE_ASSERT" #LuaJIT
gcc -O0 -ggdb3 -Lsrc -lluajit -Isrc -fPIC --shared -o allocinject.so allocinject.c #library
```

How to run:
```sh
LUA_PATH="src/?.lua;;" LD_LIBRARY_PATH=src/ src/luajit t.lua
```

</details>

The result is the assertion failure:
```
LuaJIT ASSERT lj_dispatch.c:424: lj_dispatch_ins: unbalanced stack after tracing of instruction
Program received signal SIGABRT, Aborted.
```

The backtrace of the error thrown, which prevents stack restoration:
```
(gdb) bt
#0  lj_err_throw (L=0x55555555f26b <lj_err_str+76>, errcode=32767) at lj_err.c:769
#1  0x000055555555f60f in lj_err_mem (L=0x7ffff7ca2380) at lj_err.c:824
#2  0x00005555555b3945 in lj_mem_realloc (L=0x7ffff7ca2380, p=0x0, osz=0, nsz=2084) at lj_gc.c:867
#3  0x00005555555621ca in lj_str_alloc (L=0x7ffff7ca2380, str=0x7ffff7caf6f0 'x' <repeats 200 times>..., len=2056, hash=441046516, hashalg=0) at lj_str.c:278
#4  0x00005555555625fa in lj_str_new (L=0x7ffff7ca2380, str=0x7ffff7caf6f0 'x' <repeats 200 times>..., lenx=2056) at lj_str.c:350
#5  0x00005555555b51d1 in lj_buf_cat2str (L=0x7ffff7ca2380, s1=0x7ffff7caea48, s2=0x7ffff7cac310) at lj_buf.c:287
#6  0x000055555564a5bf in fold_bufput_kgc (J=0x7ffff7ca26c0) at lj_opt_fold.c:637
#7  0x00005555556516a4 in lj_opt_fold (J=0x7ffff7ca26c0) at lj_opt_fold.c:2570
#8  0x00005555555deb8e in rec_cat (J=0x7ffff7ca26c0, baseslot=2, topslot=3) at lj_record.c:2119
#9  0x00005555555d3e8c in lj_record_ret (J=0x7ffff7ca26c0, rbase=0, gotresults=1) at lj_record.c:1023
#10 0x00005555555e2e9e in lj_record_ins (J=0x7ffff7ca26c0) at lj_record.c:2591
#11 0x0000555555591bfa in trace_state (L=0x7ffff7ca2380, dummy=0x0, ud=0x7ffff7ca26c0) at lj_trace.c:705
#12 0x00005555555ac504 in lj_vm_cpcall ()
#13 0x00005555555920dc in lj_trace_ins (J=0x7ffff7ca26c0, pc=0x7ffff7cac3b0) at lj_trace.c:764
#14 0x0000555555569f18 in lj_dispatch_ins (L=0x7ffff7ca2380, pc=0x7ffff7cac3b4) at lj_dispatch.c:423
#15 0x00005555555adeb4 in lj_vm_inshook ()
#16 0x000055555557bc9d in lua_pcall (L=0x7ffff7ca2380, nargs=0, nresults=-1, errfunc=2) at lj_api.c:1151
#17 0x000055555555cb46 in docall (L=0x7ffff7ca2380, narg=0, clear=0) at luajit.c:122
#18 0x000055555555d55f in handle_script (L=0x7ffff7ca2380, argx=0x7fffffffd4e0) at luajit.c:292
#19 0x000055555555e290 in pmain (L=0x7ffff7ca2380) at luajit.c:550
#20 0x00005555555ac10e in lj_BC_FUNCC ()
#21 0x000055555557c084 in lua_cpcall (L=0x7ffff7ca2380, func=0x55555555e0d6 <pmain>, ud=0x0) at lj_api.c:1179
#22 0x000055555555e3d7 in main (argc=2, argv=0x7fffffffd4d8) at luajit.c:581
```

It looks like these lines should be cpcalled as well, as it was done for the #1234:
https://github.com/LuaJIT/LuaJIT/blob/97813fb924edf822455f91a5fbbdfdb349e5984f/src/lj_record.c#L2106-L2121

**Comment by MikePall** [comment]
Fixed. Thanks!
