### ISSUE TITLE
LuaJIT segfault on MIPS

### ISSUE THREAD

**Issue by jpc** [LuaJIT/LuaJIT#441]
Hi,

I am running a fairly big C/Lua application (with lots of green threads based on coroutines) using Lua 5.1 on MIPS and MIPSEL (OpenWRT with musl-libc) and wanted to start using LuaJIT. Unfortunately my app segfaults after several seconds every time I run it.

I managed to make a simplified test case which does not depend on any of my own C and Lua modules. The reproducibility is not 100% but depending on the `hotloop` option it triggers a segfault at least once every 5-10 runs. It works perfectly every time on mac OS and also when I run it on MIPSEL under gdb. I am using LuaJIT (git commit fe651bf6e2b4d02b624be3c289378c08bab2fa9b) on MIPSEL built with the OpenWRT toolchain (https://github.com/LoEE/packages/tree/luajit/lang/luajit).

I made a testbench for it using `qemu-system-mipsel` and the `malta` OpenWRT platform:
```
qemu-system-mipsel -machine malta -kernel /Volumes/OpenWRT/bin/targets/malta/le/openwrt-malta-le-vmlinux-initramfs.elf -nographic -m 128 -nic user -nic user,net=192.168.1.0/24,hostfwd=tcp::22325-192.168.1.1:22
rsync -av luajit-sigsegv.lua mips-vm: && ssh -tt mips-vm 'luajit -jdump=+rsx,dump2.html luajit-sigsegv.lua; false'
```

The program should print numbers from 1 to 200. In case of error it stops at `112` or `36` (with `-Ohotloop=18`). I've attached the code and dump files (for `-Ohotloop=18`): [sources.zip](https://github.com/LuaJIT/LuaJIT/files/2345867/sources.zip) + the OpenWrt image I used: [openwrt-malta-le-vmlinux-initramfs.elf.zip](https://github.com/LuaJIT/LuaJIT/files/2345870/openwrt-malta-le-vmlinux-initramfs.elf.zip). 

The kernel log messages (I always get the same address and register contents):
```
[ 1541.895560] do_page_fault(): sending SIGSEGV to luajit for invalid write access to 0000000c
[ 1541.897141] epc = 004273bc in luajit[400000+77000]
[ 1541.897725] ra  = 00429d6c in luajit[400000+77000]
```

I've run out of ideas so any pointers about what I could try next would be greatly appreciated.

**Comment by jpc** [comment]
@corsix @MikePall @lukego Sorry to call you out like that but could you give me some debugging advice on this? I would love to dive deeper into this but a JIT compiler is not something I have experience debugging. :)

I did not mention that I also tried setting the API check flags and additional asserts that are mentioned in the docs (without success). I tried running under valgrind as well but I think I got only false positives.

Why does it work correctly under gdb? Is gdb doing something funny to the state of the process that changes the way the JIT works?

**Comment by mraleph** [comment]
@jpc 

GDB disables address space randomization by default - I don't know if that matter for this particular crash. 

Does it start crashing under GDB if you do `set disable-randomization off`?

**Comment by mraleph** [comment]
It does crash for me under GDB, seemingly within LuaJIT binary itself, rather than within JIT compiled code. Maybe inside the interpreter. I am trying now to install enough packages on the image to try and build it from source.

**Comment by mraleph** [comment]
@jpc I have trying to figure things out - but given my lack of experience with OpenWRT this is just taking too much time.

Can you tell me how to run your OpenWRT image in such a way that rootfs is not limited to 60mb? I want to back it with some disk image  - so that I could install whatever packages I want on it.

**Comment by jpc** [comment]
Of course. I tried to make the OpenWRT image simple to run under Qemu and I had to put the rootfs in RAM. I think you should be able to get a bigger rootfs just by giving Qemu more RAM. Attaching and mounting another disk may be more difficult.

I will build the LuaJIT binary with debugging symbols and upload a new image. What platform are you running on? Linux? Mac OS? Maybe I could send you a toolchain for cross compilation?

**Comment by mraleph** [comment]
I thought it should not be that difficult because OpenWRT supports overlayfs - but I just could not figure out how to make that work with your image.

If you just build LuaJIT with symbols and upload that - that already should help a lot.

**Comment by jpc** [comment]
I am really sorry but I have a mess in my OpenWRT repository right now (I am rebasing everything to a new stable release) so building this new image is taking me much longer than is reasonable. I should have something better to test soon.

**Comment by jpc** [comment]
Ok, this took way longer that I expected. I had problems with everything: new perl does not crosscompile on OS X, Xcode 10 does not compile in 32bit mode anymore, qemu does not support > 256MB RAM in 32bit mode so my OpenWRT with unstripped binaries and debug symbols would not fit. I finally managed to get it under control and I got this traceback:
```
…
111
112

Program received signal SIGSEGV, Segmentation fault.
0x004273bc in lj_BC_TSETR ()
(gdb) bt
#0  0x004273bc in lj_BC_TSETR ()
#1  0x00428e1c in lj_ff_coroutine_resume ()
#2  0x00410bd4 in lua_pcall (L=0x77f171c0, nargs=<optimized out>, nresults=-1, errfunc=<optimized out>) at lj_api.c:1129
#3  0x004039c8 in docall (L=0x77f171c0, narg=0, clear=0) at luajit.c:121
#4  0x00404bfc in handle_script (argx=<optimized out>, L=0x77f171c0) at luajit.c:292
#5  pmain (L=0x77f171c0) at luajit.c:553
#6  0x0042802c in lj_BC_FUNCC ()
#7  0x00410c44 in lua_cpcall (L=<optimized out>, func=<optimized out>, ud=<optimized out>) at lj_api.c:1153
#8  0x00403278 in main (argc=3, argv=0x7fffedc4) at luajit.c:582
```

I now remember that these are the same functions I had in tracebacks on real MIPS when running my custom Lua-based framework with the full application in March.

I've got new images with gdb, and an unstripped luajit: [openwrt-mips-malta-le.zip](https://github.com/LuaJIT/LuaJIT/files/2475721/openwrt-mips-malta-le.zip)

The new qemu command line is:
```
qemu-system-mipsel -machine malta -nographic -m 256 \
  -kernel /Volumes/OpenWRT/bin/targets/malta/le/openwrt-malta-le-vmlinux.elf \
  -hda /Volumes/OpenWRT/bin/targets/malta/le/openwrt-malta-le-root.squashfs \
  -append 'root=/dev/sda' \
  -nic user -nic user,net=192.168.1.0/24,hostfwd=tcp::22325-192.168.1.1:22
```

**Comment by jpc** [comment]
9c1b637898f38dd4606da08ba1a82a174c3e64b6 indeed fixed it, thanks a lot!
