### ISSUE TITLE
Bytecode loader crash on 32bit platforms

### ISSUE THREAD

**Issue by boolking** [LuaJIT/LuaJIT#549]
# Description
On branch v2.1(commit 0bee44c9dc9bee64d1143aa0febd2b61819d35bd) and 32bit platforms(x86 linux, ARM android), loading lua module compiled in C code and linked as shared library will cause a crash.

It **WOKS** on master branch.

# Root cause
When the luaJIT_BC_* symbol in shared library is loaded into memory, and the address is higher than 0x80000100, the pe pointer of LexState will [wrap around](https://github.com/LuaJIT/LuaJIT/blob/0bee44c9dc9bee64d1143aa0febd2b61819d35bd/src/lj_lex.c#L51) and become smaller than p. In bcread_fill() called by [bcread_want()](https://github.com/LuaJIT/LuaJIT/blob/0bee44c9dc9bee64d1143aa0febd2b61819d35bd/src/lj_bcread.c#L101), [memcpy()](https://github.com/LuaJIT/LuaJIT/blob/0bee44c9dc9bee64d1143aa0febd2b61819d35bd/src/lj_bcread.c#L64) is called with a very [large size](https://github.com/LuaJIT/LuaJIT/blob/0bee44c9dc9bee64d1143aa0febd2b61819d35bd/src/lj_bcread.c#L57) and causes bus error on x86 and segmentation fault on ARM android.

# Patch
I am using following patch to walkaround:
```patch
diff --git a/src/lj_bcread.c b/src/lj_bcread.c
index 48c5e7c..c5ef13e 100644
--- a/src/lj_bcread.c
+++ b/src/lj_bcread.c
@@ -90,14 +90,14 @@ static LJ_NOINLINE void bcread_fill(LexState *ls, MSize len, int need)
 /* Need a certain number of bytes. */
 static LJ_AINLINE void bcread_need(LexState *ls, MSize len)
 {
-  if (LJ_UNLIKELY(ls->p + len > ls->pe))
+  if (LJ_UNLIKELY(ls->p + len > ls->pe) && (ls->p <= ls->pe))
     bcread_fill(ls, len, 1);
 }
 
 /* Want to read up to a certain number of bytes, but may need less. */
 static LJ_AINLINE void bcread_want(LexState *ls, MSize len)
 {
-  if (LJ_UNLIKELY(ls->p + len > ls->pe))
+  if (LJ_UNLIKELY(ls->p + len > ls->pe) && (ls->p <= ls->pe))
     bcread_fill(ls, len, 0);
 }
```

# Detailed information
Compile luajit on linux-x86_x64 with following command line:
```
make HOST_CC='gcc -m32' TARGET_CFLAGS='-m32' TARGET_LDFLAGS='-m32' TARGET_SHLDFLAGS='-m32'
```
And compile a.lua into C code/shared library and load it:
```shell
cat > a.lua <<EOF
print('hello')
EOF

pushd src
./luajit -b ../a.lua ../a.c
popd
mv a.lua a.bak
gcc -m32 -fPIC -shared a.c -o a.so
src/luajit -e 'require "a"'
```

After added debug information, gdb call stack:
```
#0  0xf7dfa424 in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xffffd110 in ?? ()
#2  0x5658c66d in bcread_want (len=13, ls=0xffffcfb0) at lj_bcread.c:101
#3  bcread_header (ls=0xffffcfb0) at lj_bcread.c:391
#4  0x5658c8bf in lj_bcread (ls=0xffffcfb0) at lj_bcread.c:428
#5  0x565727df in cpparser (L=0xf7c941c0, dummy=0x0, ud=0xffffcfb0) at lj_load.c:41
#6  0x565814ce in lj_vm_cpcall ()
#7  0x5657290d in lua_loadx (L=0xf7c941c0, reader=0x56572be8 <reader_string>, data=0xffffd068, chunkname=0xf7c9b110 "", mode=0x0) at lj_load.c:58
#8  0x56572c71 in luaL_loadbufferx (L=0xf7c941c0, buf=0xf7fcc440 <luaJIT_BC_a> "\033LJ\002\002#\002", size=2147483392, name=0xf7c9b110 "", mode=0x0) at lj_load.c:143
#9  0x56572cab in luaL_loadbuffer (L=0xf7c941c0, buf=0xf7fcc440 <luaJIT_BC_a> "\033LJ\002\002#\002", size=2147483392, name=0xf7c9b110 "") at lj_load.c:149
#10 0x565c98f0 in ll_loadfunc (L=0xf7c941c0, path=0xf7c95d30 "./a.so", name=0xf7c9b110 "", r=0) at lib_package.c:258
#11 0x565c9f64 in lj_cf_package_loader_c (L=0xf7c941c0) at lib_package.c:381
#12 0x565811aa in lj_BC_FUNCC ()
#13 0x565679d2 in lua_call (L=0xf7c941c0, nargs=1, nresults=1) at lj_api.c:1111
#14 0x565ca3c0 in lj_cf_package_require (L=0xf7c941c0) at lib_package.c:448
#15 0x565811aa in lj_BC_FUNCC ()
#16 0x56567a5e in lua_pcall (L=0xf7c941c0, nargs=0, nresults=0, errfunc=2) at lj_api.c:1129
#17 0x565595f5 in docall (L=0xf7c941c0, narg=0, clear=1) at luajit.c:121
#18 0x56559975 in dostring (L=0xf7c941c0, s=0xffffd566 "require \"a\"", name=0x565e3d45 "=(command line)") at luajit.c:175
#19 0x5655a858 in runargs (L=0xf7c941c0, argv=0xffffd3e4, argn=3) at luajit.c:459
#20 0x5655ab87 in pmain (L=0xf7c941c0) at luajit.c:549
#21 0x565811aa in lj_BC_FUNCC ()
#22 0x56567baf in lua_cpcall (L=0xf7c941c0, func=0x5655aa04 <pmain>, ud=0x0) at lj_api.c:1153
#23 0x5655acda in main (argc=3, argv=0xffffd3e4) at luajit.c:582

```

gdb trace:

```
(gdb) file src/luajit
(gdb) set args -e 'require "a"'
(gdb) b lj_bcread.c:58
(gdb) r
(gdb) p ls->pe
$1 = 0x77fcc340 <error: Cannot access memory at address 0x77fcc340>
(gdb) p ls->p
$2 = 0xf7fcc441 <luaJIT_BC_a+1> "LJ\002\002#\002"
(gdb) p /x n
$3 = 0x7ffffeff
```

**Comment by MikePall** [comment]
Thank you for the detailed and well-formatted bug report!
I've committed a fix.
