### ISSUE TITLE
asm_loop_fixup: Assertion `((intptr_t)target & 15) == 0' failed

### ISSUE THREAD

**Issue by spacewander** [LuaJIT/LuaJIT#556]
Reproducible script:
```lua
local dump = require "jit.dump"
dump.on("abimsrtx", nil)
local template = require("template")
local ngx_tpl = [=[
    {% if with_module_status then %}
    {% end %}

    {% if enable_admin and not port_admin then %}
    location /admin {
        {%if allow_admin then%}
            {% for _, allow_ip in ipairs(allow_admin) do %}
            allow {*allow_ip*};
            {% end %}
            deny all;
        {%end%}
    }
    {% end %}
]=]
template.compile(ngx_tpl)
```

The `template` module is from https://github.com/bungle/lua-resty-template.

With this script I got:
```
---- TRACE 1 start template.lua:72
0005  UGET     2   0      ; sub       (template.lua:73)
0006  MOV      4   0       (template.lua:73)
0007  MOV      5   1       (template.lua:73)
0008  MOV      6   1       (template.lua:73)
0009  CALL     2   2   4       (template.lua:73)
0000  . FUNCC               ; string.sub
0010  ISEQS    2   0      ; " "       (template.lua:74)
0011  JMP      3 => 0018
0018  SUBVN    1   1   0  ; 1       (template.lua:75)
0019  JMP      3 => 0001       (template.lua:75)
0001  KSHORT   2   0       (template.lua:72)
0002  ISGE     2   1       (template.lua:72)
0003  JMP      2 => 0022
0004  LOOP     2 => 0022       (template.lua:72)
luajit: lj_asm_x86.h:2819: asm_loop_fixup: Assertion `((intptr_t)target & 15) == 0' failed.
[1]    26065 abort (core dumped)  luajit x.lua
```

The backtrace:
```
(gdb) bt
#0  0x00007f2933759e97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f293375b801 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f293374b39a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f293374b412 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000559713c7568a in asm_loop_fixup (as=0x7fff62f0f1d0) at lj_asm_x86.h:2819
#5  asm_loop (as=as@entry=0x7fff62f0f1d0) at lj_asm.c:1584
#6  0x0000559713c78589 in asm_ir (ir=0x7f29344e37f0, as=0x7fff62f0f1d0) at lj_asm.c:1615
#7  lj_asm_trace (J=J@entry=0x7f29344cd688, T=T@entry=0x7f29344cd688) at lj_asm.c:2358
#8  0x0000559713c4680a in trace_state (L=0x7f29344cd378, dummy=<optimized out>, ud=0x7f29344cd688) at lj_trace.c:698
#9  0x0000559713c52189 in lj_vm_cpcall () at buildvm_x86.dasc:1321
#10 0x0000559713c4757f in lj_trace_ins (J=J@entry=0x7f29344cd688, pc=pc@entry=0x7f29344dac18) at lj_trace.c:730
#11 0x0000559713c35ae2 in lj_dispatch_ins (L=0x7f29344cd378, pc=0x7f29344dac1c) at lj_dispatch.c:424
#12 0x0000559713c53ccb in lj_vm_inshook () at buildvm_x86.dasc:2588
#13 0x0000559713c3d722 in lua_pcall (L=0x7f29344cd378, nargs=0, nresults=-1, errfunc=<optimized out>) at lj_api.c:1129
#14 0x0000559713c2fa75 in docall (L=0x7f29344cd378, narg=0, clear=0) at luajit.c:121
#15 0x0000559713c30bd0 in handle_script (argx=<optimized out>, L=0x7f29344cd378) at luajit.c:292
#16 pmain (L=0x7f29344cd378) at luajit.c:553
#17 0x0000559713c51d93 in lj_BC_FUNCC () at buildvm_x86.dasc:898
#18 0x0000559713c3d77b in lua_cpcall (L=<optimized out>, func=<optimized out>, ud=<optimized out>) at lj_api.c:1153
#19 0x0000559713c30cb6 in main (argc=2, argv=0x7fff62f0f998) at luajit.c:582
```

The luajit is built with
```
make -j16 TARGET_STRIP=@: CCDEBUG=-g Q= XCFLAGS='-msse4.2 -DLUA_USE_APICHECK -DLUA_USE_ASSERT -DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -DLUAJIT_ENABLE_GC64 -O1 -ggdb3 -fno-omit-frame-pointer'
```

Can be reproduced with the code from the latest v2.1 branch.

**Comment by MikePall** [comment]
Fixed.

**Comment by spacewander** [comment]
For guys who want to apply the fix, the commit is https://github.com/LuaJIT/LuaJIT/commit/522d2073da4be2af79db4728cbb375db0fbdfc48
